### ISSUE TITLE
Documentation: Diagrams

### ISSUE THREAD

**Issue by SteaneMurphy** [SteaneMurphy/T3A2_FullStackApp#3]
- [x] Dataflow Diagram
- [x] Application Architecture Diagram

**Comment by Minabishay123** [comment]
**Discussion Held:**
- **Date:** 15/08/2024
- **Participants:** Mina, James, William
- **Topic:** Review and Update of Dataflow Diagram for TravelMate Itinerary Builder

**Key Points Discussed:**
1. **Dataflow Diagram Update:** Reviewed the existing dataflow diagram and identified areas that needed clarification, particularly how information such as login credentials, authentication tokens, and itinerary details move between components.

2. **Purpose of Update:** The update was necessary to ensure that the team has a clear understanding of the interactions between the system components during the Login/Registration process and the Itinerary Management process.

3. **Agile (Scrum) Changes Implemented:**
   - **Backlog Update:** Added a task to the product backlog to revise the dataflow diagram based on the discussion.
   - **Sprint Planning:** Prioritised this task for inclusion in the current sprint to ensure it aligns with the ongoing development efforts.
   - **Review and Retrospective:** Scheduled a review session at the end of the sprint to confirm that the updated diagram accurately reflects the system's data flow and meets the project's needs.

**Outcome:**
- A revised dataflow diagram was added, detailing how information like login credentials, authentication tokens, and itinerary details move between components such as the Browser, Authentication Service (JWT), User Data Store, and Itinerary Data Store.

**Comment by Minabishay123** [comment]
**Discussion Held:**
- **Date:** 15/08/2024
- **Participants:** Mina, James, William
- **Topic:** Application Architecture Diagram Update and Agile (Scrum) Adjustments

**Key Points Discussed:**
1. **Architecture Diagram Update:** Reviewed the need to include appropriate symbols in the Application Architecture Diagram, such as:
   - **Shield Icon:** For JWT (JSON Web Token), representing security and authentication.
   - **Gear Icon:** For the backend processes, indicating business logic and processing.
   - **Server Rack Icon:** For the web server, representing the infrastructure handling requests.
   - **Cylinders:** For data storage, representing the Database (MongoDB).

2. **User Roles and Interfaces:** Agreed to include distinct representations for different user roles:
   - **Admin User and Normal User:** Both roles will be represented and their respective interfaces (Admin Visual Interface and User Visual Interface) will be highlighted in the diagram.
   - **Web Server:** Handles requests from both admin and normal users, connecting them to the backend and database.

3. **Agile (Scrum) Changes Implemented:**
   - **Backlog Update:** Added a task to the product backlog to revise the architecture diagram with the newly agreed symbols and elements.
   - **Sprint Planning:** Prioritised this task for the current sprint to ensure that the visual representations align with the updated architecture and data flow.
   - **Review and Retrospective:** Planned a review at the end of the sprint to assess the accuracy of the updated diagram and its alignment with the project goals.

**Outcome:**
- The Application Architecture Diagram was revised to include appropriate symbols, such as the Shield Icon for JWT, Gear Icon for the backend, and Server Rack Icon for the web server.
- The diagram now clearly represents different user roles (Admin and Normal User) and their respective interactions with the system components.
