### ISSUE TITLE
Documentation: Screenshots

### ISSUE THREAD

**Issue by SteaneMurphy** [SteaneMurphy/T3A2_FullStackApp#5]
- [x] Initial Project screenshot
- [x] Discord Webhooks screenshot
- [x] Task view (a few examples)
- [x] Overall project screenshot
- [x] Task assignment examples
- [x] CI/CD evidence

**Comment by SteaneMurphy** [comment]
PART A Before Completion:

- [x] Documentation: General
- [x] Wireframes
- [x] Diagrams
- [x] User Stories

PART A At Completion:

- [ ] Documentation: General
- [ ] Wireframes
- [ ] Diagrams
- [ ] User Stories

**Comment by Minabishay123** [comment]
**Discussion Held:**
- **Date:** 16/08/2024
- **Participants:** Mina, James, William
- **Topic:** Application Architecture Diagram Update and Agile (Scrum) Adjustments

**Key Points Discussed:**
1. **Architecture Diagram Update:** Reviewed the need to include appropriate symbols in the Application Architecture Diagram, such as:
   - **Lock Icon:** For JWT (JSON Web Token), representing security and authentication.
   - **Server rack icon:** For the backend processes, indicating business logic and processing.
   - **Server Rack with web globe Icon:** For the web server, representing the infrastructure handling requests.
   - **Cylinders:** For data storage, representing the Database (MongoDB).

2. **User Roles and Interfaces:** Agreed to include distinct representations for different user roles:
   - **Admin User and Normal User:** Both roles will be represented and their respective interfaces (Admin Visual Interface and User Visual Interface) will be highlighted in the diagram.
   - **Web Server:** Handles requests from both admin and normal users, connecting them to the backend and database.

3. **Agile (Scrum) Changes Implemented:**
   - **Backlog Update:** Added a task to the product backlog to revise the architecture diagram with the newly agreed symbols and elements.
   - **Sprint Planning:** Prioritised this task for the current sprint to ensure that the visual representations align with the updated architecture and data flow.
   - **Review and Retrospective:** Planned a review at the end of the sprint to assess the accuracy of the updated diagram and its alignment with the project goals.

**Outcome:**
- The Application Architecture Diagram was revised to include appropriate symbols.
- The diagram now clearly represents different user roles (Admin and Normal User) and their respective interactions with the system components.
